# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Producte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id_producte', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('caracteristiques', models.TextField()),
                ('restriccio', models.TextField()),
                ('imatge', models.ImageField(max_length=200, upload_to='productes')),
                ('preu', models.DecimalField(decimal_places=2, help_text='preu producte', max_digits=7)),
                ('stock', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productes.Marca_Producte')),
            ],
        ),
        migrations.CreateModel(
            name='Tipus_Producte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producte',
            name='tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productes.Tipus_Producte'),
        ),
    ]
