# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('num_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('estat', models.CharField(choices=[('R', 'Rebuda'), ('P', 'Processant'), ('F', 'Finalitazada'), ('E', 'Entregada'), ('A', 'Anulada')], help_text='Estat_Comanda', max_length=1)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Linia',
            fields=[
                ('id_linia', models.AutoField(primary_key=True, serialize=False)),
                ('quantitat', models.IntegerField()),
                ('descompte', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='descompte', max_digits=4, null=True)),
                ('id_comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandes.Comanda')),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productes.Producte')),
            ],
        ),
    ]
